plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
rootProject.name = 'ct'

//include 'kafka:producer'
['producer','consumer','common', 'producer-spring-cloud', 'consumer-spring-cloud'].forEach { proj ->
    {
        include(":kafka:${proj}")
        project(":kafka:${proj}").projectDir = file("kafka/${proj}")
    }
}

['gRPC_Core','gRPC_server'].forEach { proj ->
    {
        include(":gRPC:${proj}")
        project(":gRPC:${proj}").projectDir = file("gRPC/${proj}")
    }
}