// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.35.1

package org.example.grpc_server.dto;

@com.google.protobuf.Generated
public interface GetOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
