// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.35.1

package org.example.grpc_server.dto;

@com.google.protobuf.Generated
public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string brand = 3;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 3;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>string price = 4;</code>
   * @return The price.
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 4;</code>
   * @return The bytes for price.
   */
  com.google.protobuf.ByteString
      getPriceBytes();
}
