// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.35.1

package org.example.grpc_server.dto;

@com.google.protobuf.Generated
public final class OrderOuterClass extends com.google.protobuf.GeneratedFile {
  private OrderOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "OrderOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Orders_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Orders_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\"\037\n\006Orders\022\025\n\005order\030\001 \003(\0132\006" +
      ".Order\"\035\n\017GetOrderRequest\022\n\n\002id\030\001 \001(\t\"@\n" +
      "\022CreateOrderRequest\022\014\n\004name\030\001 \001(\t\022\r\n\005bra" +
      "nd\030\002 \001(\t\022\r\n\005price\030\003 \001(\t\"\007\n\005Empty\"?\n\005Orde" +
      "r\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005brand\030\003 \001" +
      "(\t\022\r\n\005price\030\004 \001(\t2\242\002\n\014OrderService\022%\n\tge" +
      "tOrders\022\020.GetOrderRequest\032\006.Order\022+\n\014cre" +
      "ateOrders\022\023.CreateOrderRequest\032\006.Order\022\037" +
      "\n\014getAllOrders\022\006.Empty\032\007.Orders\022-\n\031serve" +
      "rSideStreamingOrders\022\006.Empty\032\006.Order0\001\022-" +
      "\n\031clientSideStreamingOrders\022\006.Order\032\006.Em" +
      "pty(\001\022?\n\034bidirectionalStreamingOrders\022\023." +
      "CreateOrderRequest\032\006.Order(\0010\001B\037\n\033org.ex" +
      "ample.grpc_server.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Orders_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_Orders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Orders_descriptor,
        new java.lang.String[] { "Order", });
    internal_static_GetOrderRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_GetOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetOrderRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CreateOrderRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_CreateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CreateOrderRequest_descriptor,
        new java.lang.String[] { "Name", "Brand", "Price", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Order_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "Id", "Name", "Brand", "Price", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
