// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.35.1

package org.example.dto;

@com.google.protobuf.Generated
public interface OrdersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Orders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Order order = 1;</code>
   */
  java.util.List<org.example.dto.Order> 
      getOrderList();
  /**
   * <code>repeated .Order order = 1;</code>
   */
  org.example.dto.Order getOrder(int index);
  /**
   * <code>repeated .Order order = 1;</code>
   */
  int getOrderCount();
  /**
   * <code>repeated .Order order = 1;</code>
   */
  java.util.List<? extends org.example.dto.OrderOrBuilder> 
      getOrderOrBuilderList();
  /**
   * <code>repeated .Order order = 1;</code>
   */
  org.example.dto.OrderOrBuilder getOrderOrBuilder(
      int index);
}
